// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  main

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( ProductInfo ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ProductInfo ) UnmarshalJSON([]byte) error { return nil }
func ( ProductInfo ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ProductInfo ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ProductInfo *ProductInfo

func ( teleInfo ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* teleInfo ) UnmarshalJSON([]byte) error { return nil }
func ( teleInfo ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* teleInfo ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_teleInfo *teleInfo
